FROM alpine:3.8

RUN apk add --no-cache \
        g++ \
        gcc \
        git \
        bash \
        file \
        nasm \
        make \
        automake \
        autoconf \
        gettext \
        libjpeg \
        libpng \
        libpng-dev \
        libtool \
        libnotify
